name: Pulblish to PyPI

on:
 release: 
   types: [prereleased, released]
 workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Set env"
        run: |
         if [ -n "${{ github.event.inputs.version }}" ]; then
           echo "RELEASE_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
           git tag ${{ github.event.inputs.version }}
         else
           echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
         fi
      - name: echo version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry 
      - name: Add Poetry Plugin
        run: |
          pip install poetry-version-plugin
      - name: PyPI Settings
        run: |
          poetry config pypi-token.pypi ${{secrets.PYPI_TOKEN}}

      - name: Build Poetry
        run: |
          poetry build
          poetry publish